/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_aachen_comsys_assignment2_data_MealPlan */

#ifndef _Included_de_rwth_aachen_comsys_assignment2_data_MealPlan
#define _Included_de_rwth_aachen_comsys_assignment2_data_MealPlan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_rwth_aachen_comsys_assignment2_data_MealPlan
 * Method:    requestUrl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_rwth_1aachen_comsys_assignment2_data_MealPlan_requestUrl
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
